VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsTransactionInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' clsTransactionInfo
Option Explicit

Public DataInreg As String
Public DataOper As String
Public Valoare As String
Public Comision As String
Public NumarCard As String
Public Retea As String
Public TipC As String
Public CodAut As String
Public RRN As String
Public Document As String

