VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "clsTransactionInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' clsTransactionInfo
Option Explicit

Public DataInreg As Date
Public DataOper As Date
Public Valoare As Currency
Public Comision As Currency
Public NumarCard As String
Public Retea As String
Public TipC As String
Public CodAut As String
Public RRN As String
Public Document As String